#script adapted from this example: https://community.esri.com/t5/arcgis-api-for-python-blog/using-the-arcgis-api-for-python-to-create-a-view-from-a-hosted/ba-p/902966
#no effects applied on our layer view

from arcgis.gis import GIS
from arcgis.features import FeatureLayerCollection

def main():

    #connecting to AGOL
    gis = GIS('home')

    #searching the parent feature layer
    layer_name = "Crop Production cleaned and weighted household data"
    search_results = gis.content.search(query="title: " + layer_name, item_type="Feature *")[0]

    view_flc = FeatureLayerCollection.fromitem(search_results)

    #first update the query
    update_dict_rows = {"viewDefinitionQuery": "admin0_3isocode is 'COL'"}
    view_flc.manager.update_definition(update_dict_rows)

    #then modify visibility: turn off field 'admin_level'
    update_dict_col = """{"fields": [
    {
      "name": "survey_id",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "survey_id",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin_name",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin name",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin_level",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin_level",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin0_3isocode",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin0_3isocode",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin0_code",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin0_code",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin0_desc",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin0_desc",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin1_code",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin1_code",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin1_desc",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin1_desc",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin2_code",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin2_code",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "admin2_desc",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "admin2_desc",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "hhh_gender",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "household head gender",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "hhh_gender_male",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "household head gender male",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "hhh_gender_female",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "household head gender female",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "hh_size",
      "type": "esriFieldTypeInteger",
      "actualType": "int",
      "alias": "household size ",
      "sqlType": "sqlTypeInteger",
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these agricultural activities are you involved in? \\\"Yes\\\" if \\\"Crop production\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "livestock_prod",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "livestock production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these agricultural activities are you involved in? \\\"Yes\\\" if \\\"Livestock production\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "fisheries_prod",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "fisheries production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these agricultural activities are you involved in? \\\"Yes\\\" if \\\"Fisheries/aquaculture\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "forestry_prod",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "forestry production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these agricultural activities are you involved in? \\\"Yes\\\" if \\\"Reliance on forest products/natural resources\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "no_agric_prod",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "no agricultural production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these agricultural activities are you involved in? \\\"Yes\\\" if \\\"None\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "agri_type",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "agricultural production type",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Main agricultural activity which household  involved in. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "weight",
      "type": "esriFieldTypeDouble",
      "actualType": "float",
      "alias": "weight",
      "sqlType": "sqlTypeFloat",
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Positive values associated with each observations, which are used to ensure that the metrics derived from the dataset are representative of the population of interest.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "percent_",
      "type": "esriFieldTypeDouble",
      "actualType": "float",
      "alias": "percent",
      "sqlType": "sqlTypeFloat",
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "hh_agri_status",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "household agricultural status",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Indicates if respondent involved in any agricultural activity. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "hh_agri_status_agri",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "agricultural household",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "hh_agri_status_nonagri",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "non_agricultural household",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "income_change",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "income change",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Has your overall income in the past three months changed compared to the same period last year? \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "income_change_decreased",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "income change decreased",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "income_change_increased",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "income change increased",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "income_change_nochange",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "income change nochange",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "income_change_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "income change other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "particular_shock_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock1 sickness or death of households member[s]",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock2 lost employment or income losses",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock3 restriction measures",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock4 increased prices",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_5",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock5 reduction in own production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_6",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock6 delay in production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_7",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock7 higher production costs",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_8",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock8 sudden reduction in access to credit",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_9",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock9 natural hazard ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_10",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock10 insecurity/conflict",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_11",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock11 no particular shock ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_12",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock12 other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_13",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock13 responder don't know",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "particular_shock_14",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "shock14 refused to answer ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Has your household faced any additional shock in the last 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "crop_planted_area_comp",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop planted area compared to last year",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"What is the area planted or you are planning to plant with main crop compared to last year?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "crop_planted_area_comp_less",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop planted area less",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_planted_area_comp_more",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop planted area more",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_planted_area_comp_same",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop planted area same",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_planted_area_comp_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop planted area na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_planted_area_comp_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop planted area other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Have you faced any unusual difficulty with your crop production in the past three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "crop_prod_diff_minor",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production difficulty minor",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_significant",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production difficulty significant",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_no",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production difficulty no",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production difficulty na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_main",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main crop production difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these unusual difficulties (if any) have you faced THE MOST in the past three months with your crop production?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "crop_prod_diff_sec",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "second crop production difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these unusual difficulties (if any) have you faced THE 2ND MOST in the past three months with your crop production?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "crop_prod_diff_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff1 dryspell/drought",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff2 heavy rains/floods ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff3 hail/storms/strong winds",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff4 outbreak of pests or diseases",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_5",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff5 difficulty to access seeds",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_6",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff6  difficulty to access fertilizers/pesticide",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_7",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff7 difficulty to access tools/machinery",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_8",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff8 difficulty to access finance/credit",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_9",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff9 labour not available",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_10",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff10 labour too expensive or income insufficient to hire labour",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_11",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff11 access to land restricted by containment measures",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_12",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff12 lower irrigation than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_13",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff13 household members sick",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_14",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff14 lack of perspective on possibility to sell products or on prices ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_diff_15",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "cropdiff15 other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "pests_diseases",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "pests diseases",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which pests or diseases affected your crop production in the past three months?  (Asked only if \\\"main crop production difficulty\\\" or \\\"second main crop production difficulty\\\" contains \\\"Outbreak of pests or diseases\\\") \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sad",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seed access difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Have you been facing any particular difficulty accessing seeds over the past three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sad_yes",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seed access difficulty yes",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_no",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seed access difficulty no",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seed access difficulty na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seed access difficulty other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_main",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main seed access difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which unusual difficulties, if any, have you faced in accessing seeds over the past three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sad_sec",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "second seed access difficulty ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: What has been the second main difficulty in accessing seeds over the past three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sad_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff1 unavailable from vendors",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff2 unavailable from local market",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff3 varieties usually used unavailable",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff4 no longer provided by aid or subsidies",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_5",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff5 prices of seeds higher than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_6",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff6 household income insufficient",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_7",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff7 not able or not allowed to go to market for seeds",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_8",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff8 seed lenders don't have seeds to credit",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_9",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff9 other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_10",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff10 no second difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sad_11",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "seedaccessdiff11 na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_comp",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production compared to last year/a normal year",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: What is or what do you expect your main crop production to be compared to [last year/a normal year]?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "crop_prod_comp_higher",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production compared higher",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_comp_lower",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production compared lower",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_comp_same",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production compared same",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_comp_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production compared na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "crop_prod_comp_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "crop production compared  other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animal raising difficulty ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Have you faced any unusual difficulty with these animals in the past three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "animal_raising_diff_minor",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animal raising difficulty  minor",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "animal_raising_diff_significant",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animal raising difficulty  significant",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_no",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animal raising difficulty  no",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animal raising difficulty  na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_main",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main animal raising difficulty ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these unusual difficulties (if any) have you faced the most in the past three months to raise your animals?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "animal_raising_diff_sec",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "second animal raising difficulty  ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Which of these unusual difficulties (if any) have you faced the second most in the past three months to raise your animals?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "animal_raising_diff_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff1 difficulty to access feed",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff2 constrained access to pasture",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff3 constrained access to water",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff4 difficulty to access veterinary services",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_5",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff5 difficulty to access veterinary inputs",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_6",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff6 other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_raising_diff_7",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "animaldiff7 no second difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "access_feed_diff_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessfeeddiff1 prices higher than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access feed for your animals over the past three months? \\\"Yes\\\" if \\\"Prices higher than usual\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_feed_diff_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessfeeddiff2 not available from usual vendor",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access feed for your animals over the past three months? \\\"Yes\\\" if \\\"Not available from usual vendor\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_feed_diff_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessfeeddiff3 not able to access market to purchase",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access feed for your animals over the past three months? \\\"Yes\\\" if \\\"Not able to access market to purchase\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_feed_diff_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessfeeddiff4 income insufficient/unable to get credit to purchase",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access feed for your animals over the past three months? \\\"Yes\\\" if \\\"Income insufficient to purchase\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_diff_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetdiff1 prices higher than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary services for your animals over the past three months? \\\"Yes\\\" if \\\"Prices higher than usual\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_diff_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetdiff3 not able to access service provider",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary services for your animals over the past three months? \\\"Yes\\\" if \\\"Not able to access service provider\\\" selected.\\n\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_diff_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetdiff4 income insufficient to access service",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary services for your animals over the past three months? \\\"Yes\\\" if \\\"Income insufficient to access service\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_diff_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetdiff2  not available from usual service provider ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary services for your animals over the past three months? \\\"Yes\\\" if \\\"Not available from usual service provider \\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_inp_diff_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetinpdiff1 prices higher than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary inputs for your animals over the past three months? \\\"Yes\\\" if \\\"Prices higher than usual\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_inp_diff_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetinpdiff2 not available from usual vendor",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary inputs for your animals over the past three months? \\\"Yes\\\" if \\\"Not available from usual vendor\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_inp_diff_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetinpdiff3 not able to access market/shop to purchase",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary inputs for your animals over the past three months? \\\"Yes\\\" if \\\"Not able to access market/shop to purchase\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "access_vet_inp_diff_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "accessvetinpdiff4 income insufficient to purchase",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why have you been facing difficulties to access veterinary inputs for your animals over the past three months? \\\"Yes\\\" if \\\"Income insufficient to purchase\\\" selected. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "animal_comp",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "number of animals compared to the same month last year",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Compared to the same month last year, do you have more or less main animal?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "animal_comp_less",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "number of animals compared less",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_comp_more",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "number of animals compared more",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_comp_same",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "number of animals compared same",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_comp_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "number of animals compared na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "animal_comp_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "number of animals compared other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "less_animals_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals1 higher mortality due to lack of veterinary services ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year?\\n\\\"Yes\\\" if \\\"Higher mortality due to lack of veterinary services\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "less_animals_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals2 better sales than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year?\\n\\\"Yes\\\" if \\\"Better sales than usual\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "less_animals_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals3 distress sales for urgent cash needed ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year?\\n\\\"Yes\\\" if \\\"Distress sales for urgent cash needed\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "less_animals_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals4 sold animals because unable to feed them ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year?\\n\\\"Yes\\\" if \\\"Sold animals because unable to feed them\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "less_animals_5",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals5 culled animals for household consumption ",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year?\\n\\\"Yes\\\" if \\\"Culled animals for household consumption\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "less_animals_6",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals6 other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year?\\n\\\"Yes\\\" if \\\"Other\\\" selected.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "less_animals_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "reasonlessanimals other(specify)",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Why do you have fewer animals now compared to the same month last year? If \\\"Other\\\" answer option is selected, specific explanation of the reason is stored under \\\"other(specify)\\\" variable.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sales_comp",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main agriculture activity sales compared to the same period last year",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: How would you compare the level of your sales over the past three months with the same period last year?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sales_comp_higher",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main agriculture activity sales compared higher",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_comp_lower",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main agriculture activity sales compared lower",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_comp_same",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main agriculture activity sales compared same",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_comp_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main agriculture activity sales compared na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_comp_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main agriculture activity sales compared other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": " difficulty selling main agriculture activity production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Have you faced unusual difficulties to sell your [crop/livestock/fish] production in the last three months?\\n\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sales_diff_minor",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "difficulty selling main agriculture activity production minor",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_significant",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "difficulty selling main agriculture activity production significant",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_no",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "difficulty selling main agriculture activity production no",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "difficulty selling main agriculture activity production na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_main",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main difficulty selling main agriculture activity production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: What is the highest unusual difficulty you faced to sell your crop/livestock/fish production in the last three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sales_diff_sec",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "second difficulty selling main agriculture activity production",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: What is the second highest unusual difficulty you faced to sell your crop/livestock/fish production in the last three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sales_diff_1",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff1 constrained access to market",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_2",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff2 demand lower than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_3",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff3 usual traders not coming to buy prod anymore",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_4",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff4 cost of transportation higher than usual",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_5",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff5 prices too low",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_6",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff6 other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_diff_7",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "salesdiff7 No other difficulty",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "prod_destroy",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "destroy production due to lack of market and storage capacity",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Have you had to give away or destroy part of your production due to lack of marketing and storage capacity in the last three months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "prod_destroy_yes",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "destroy production due to lack of market and storage capacity yes",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "prod_destroy_no",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "destroy production due to lack of market and storage capacity no",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "prod_destroy_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "destroy production due to lack of market and storage capacity na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "prod_destroy_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "destroy production due to lack of market and storage capacity other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_price_comp",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "product price compared to last year",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"At what price are you selling your products compared to last year at the same period? \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "sales_price_comp_higher",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "product price compared to last year higher",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_price_comp_lower",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "product price compared to last year lower",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_price_comp_same",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "product price compared to last year same",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_price_comp_other",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "product price compared to last year other",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "sales_price_comp_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "product price compared to last year na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "lcsi",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "lcsi livelihood coping strategy index",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "lcsi_stress",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "lcsi_stress",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Most severe livelihood coping strategies used by household  are STRESS strategies.\\n\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "lcsi_emergency",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "lcsi_emergency",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Most severe livelihood coping strategies used by household  are EMERGENCY strategies.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "lcsi_security",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "lcsi_security",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Most severe livelihood coping strategies used by household  are SECURITY strategies.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "lcsi_crisis",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "lcsi_crisis",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Most severe livelihood coping strategies used by household  are CRISIS strategies.\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "lcsi_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "lcsi_na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"No livelihood coping strategy used by household. \",\"fieldValueType\":\"\"}"
    },
    {
      "name": "needs_assistance",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "needs assistance",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: Do you need assistance for your [crop/livestock/fisheries] production over the next 3 months?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "main_needs_assistance",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "main  needs assistance",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null,
      "description": "{\"value\":\"Question asked: What is your greatest need for assistance?\",\"fieldValueType\":\"\"}"
    },
    {
      "name": "fies",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "fies food insecurity experience scale",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "fies_modearate",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "fies_modearate",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "fies_severe",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "fies_severe",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "fies_modearate_fs",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "fies_modearate_fs",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "fies_na",
      "type": "esriFieldTypeString",
      "actualType": "nvarchar",
      "alias": "fies_na",
      "sqlType": "sqlTypeNVarchar",
      "length": 256,
      "nullable": true,
      "editable": true,
      "visible": false,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "FID",
      "type": "esriFieldTypeOID",
      "actualType": "int",
      "alias": "FID",
      "sqlType": "sqlTypeInteger",
      "nullable": false,
      "editable": false,
      "visible": true,
      "isViewOverride": false,
      "domain": null,
      "defaultValue": null
    }
  ]}"""
    view_flc.manager.update_definition(update_dict_col)

if __name__ == "__main__":
    main()